import { MainLayout } from "@/components";
import images from "@/contansts/images";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { ReactQueryClientProvider } from "./QueryClientProvider";
import { logo } from "@/components/icons";
import "@/styles/reset.css";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "iWeather",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={nunito.className} style={{ margin: 0 }}>
          {children}
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
